#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cpg -ivg" \
	mv="mvg -ivg" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
    ttui="/usr/bin/taskwarrior-tui" \
	ffmpeg="ffmpeg -hide_banner"
	# cp="cp -iv" \
	# mv="mv -iv" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
  l="exa -l" \
  ll="exa -al" \
  lsn="nnn -dcErx" # revolutionary of ls

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
  sudo="doas" \
	trem="transmission-remote" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	:q="exit" \
  pow="sudo powertop --auto-tune" \
  nafas="python -m nafas" \
  reshell="source $ZDOTDIR/.zshrc" \
  renet="sudo rc-service NetworkManager restart" \
  lapoly="bash ~/.config/polybar/scripts/launch-polybar" \
  smallpdf="gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=small.pdf "  # compress your pdf files size
	# z="zathura" \
  # n="nnn -c" \

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"
