#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

# Start some important script at this path below
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

exec dwm 2> ~/.dwm.log
$(sleep 4s && "$XDG_CONFIG_HOME/polybar/scripts/launch-polybar") &
# . "${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch-polybar"
# ssh-agent dwm 2> ~/.dwm.log
# exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) /usr/local/bin/dwm 2> ~/.dwm.log
