#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

remaps &		# run the remaps script, switching caps/esc and more; check it for more info
mpd &			  # music player daemon-you might prefer it as a service though
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
dunst &     # For notify
picom &     # picom for transparency with transient window
unclutter &	# Remove mouse when idle
xset r rate 300 50 &	# Speed xrate up
sxhkd  &    # load keymap
redshift &  # save eye from blue light
clipmenud & # clipmenu using dmenu
playerctld & # needed to auto detect player running
libinput-gestures & # touchpad gestures swipe like MacOS
pomo notify & # needed to show notify of Pomodoro session
lxpolkit & # LXDE session for some application needed
# dwmblocks & # clickable

# dwmbar & # not support click(?) output as a string
# notify-hightemp &
# /usr/bin/flameshot &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
# pidof -s openrc &&
# 	! pidof -s pulseaudio >/dev/null 2>&1 &&
# 	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
# pulseaudio --check; pulseaudio --kill; pulseaudio --start & # -D or --start &
pipewire &      # start pipwire as audio daemon
